class intro():
    def __init__(self,g):
        print(g.data)
        print("number of node is ", g.data.x.shape[0])
        print("number of feature is ", g.data.x.shape[1])
        print("number of edge is ", g.data.edge_index.shape[1])
        print("average edge number is ", g.data.edge_index.shape[1]/g.data.x.shape[0])
        print("\n\n논문의 hyper parameters은")
        print("layer : 2")
        print("hidden feature : 16")
        print("drop out : 2 layer 0.5")
        print("loss function : cross entropy")
        print("last layer activation : softmax")
        print("대략 이 형태인데 100번의 iter의 평균값으로 실험해본 결과")
        print("hidden layer feature : 32")
        print("dropout : 1 layer, 0.5")
        print("가 더 좋은 결과를 내었으므로 과제의 취지에 따라 hyper parameter를 바꿔서 실험하였다.")
        print('실험의 결과는 대략 다음과 같다.')
        print('|-------------------------------------------------------------------|')
        print('|layers | hidden feature | last layer dropout | 100 average accuracy|')
        print('|      2|              16|                  no|               69.457|')
        print('|      2|              16|                 yes|               69.344|')
        print('|      2|              32|                  no|               69.977|')
        print('|      2|              32|                 yes|               68.679|')
        print('|      3|           16,32|                  no|               66.117|')
        print('|      3|           16,16|                  no|               65.117|')
        print('|-------------------------------------------------------------------|')
